apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cloudkit-shared-base

resources:
- namespace.yaml

# Common annotations for all CloudKit components
commonAnnotations:
  cloudkit.io/organization: cloudkit
  cloudkit.io/project: shared

# Common labels for all CloudKit components
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: cloudkit
