apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cloudkit-operator
  name: cloudkit-operator-clusterorder-editor-role
rules:
  - apiGroups:
      - cloudkit.openshift.io
    resources:
      - clusterorders
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cloudkit.openshift.io
    resources:
      - clusterorders/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cloudkit-operator
  name: cloudkit-operator-clusterorder-viewer-role
rules:
  - apiGroups:
      - cloudkit.openshift.io
    resources:
      - clusterorders
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - cloudkit.openshift.io
    resources:
      - clusterorders/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cloudkit-operator
  name: cloudkit-operator-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cloudkit-operator-leader-election-role
subjects:
  - kind: ServiceAccount
    name: cloudkit-operator-controller-manager
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cloudkit-operator
  name: cloudkit-operator-leader-election-role
  namespace: default
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cloudkit-operator
  name: cloudkit-operator-manager-admin-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: cloudkit-operator-controller-manager
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cloudkit-operator
  name: cloudkit-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudkit-operator-manager-role
subjects:
  - kind: ServiceAccount
    name: cloudkit-operator-controller-manager
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudkit-operator-manager-role
rules:
  - apiGroups:
      - ''
    resources:
      - namespaces
      - serviceaccounts
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cloudkit.openshift.io
    resources:
      - clusterorders
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cloudkit.openshift.io
    resources:
      - clusterorders/finalizers
    verbs:
      - update
  - apiGroups:
      - cloudkit.openshift.io
    resources:
      - clusterorders/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - hypershift.openshift.io
    resources:
      - hostedclusters
      - nodepools
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudkit-operator-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudkit-operator-metrics-auth-role
subjects:
  - kind: ServiceAccount
    name: cloudkit-operator-controller-manager
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudkit-operator-metrics-auth-role
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudkit-operator-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
