apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lars-innabox

transformers:
- prefixTransformer.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: kustomize
    environment: development

# Include base resources (cloudkit-aap, cloudkit-operator, shared)
resources:
- ../../base

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: quay-pull-secret
  files:
  - .dockerconfigjson=files/quay-pull-secret.json
  type: kubernetes.io/dockerconfigjson

- name: cloudkit-config
  envs:
  - envs/cloudkit-config.env

- name: config-as-code-ig
  envs:
  - envs/config-as-code-ig.env

- name: config-as-code-manifest-ig
  files:
  - license.zip=files/license.zip
