apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cloudkit-development-unified

# Development environment annotations
commonAnnotations:
  environment: development

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: kustomize
    environment: development

# Include base resources (cloudkit-aap, cloudkit-operator, shared)
resources:
- ../../base/shared
- ./cloudkit-aap
- ./cloudkit-operator
- ./fulfillment-service

images:
- name: ghcr.io/innabox/fulfillment-service
  newName: quay.io/rh-ee-jkary/fulfillment-service
  newTag: latest

namespace: foobar
namePrefix: dev-

replacements:
  - source:
      kind: ServiceAccount
      name: fulfillment-controller
      fieldPath: metadata.name
    targets:
      - select:
          kind: ConfigMap
          name: fulfillment-config
        fieldPaths:
          - data.FULFILLMENT_SERVICE_ACCOUNT

# Secret generators for both components
secretGenerator:
- files:
  - .dockerconfigjson=dockerconfig.json
  name: quay-pull-secret
  type: kubernetes.io/dockerconfigjson
  options:
    disableNameSuffixHash: true

patches:
- patch: |-
    - op: replace
      path: /data/FULFILLMENT_SERVICE_URI
      value: "https://dev-fulfillment-api-foobar.apps.hcp.local.lab"
    - op: replace
      path: /data/FULFILLMENT_SERVICE_ACCOUNT
      value: "dev-client"
  target:
    kind: ConfigMap
    name: fulfillment-config
