apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: innabox-devel

# This applies a name prefix to cluster-scoped resources (ClusterRoles,
# ClusterRoleBindings) but does not modify namespaced resources.
transformers:
- prefixTransformer.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: kustomize
    environment: development

resources:
- ../../base

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:

# This expects to find quay credentials in
# files/quay-pull-secret.json.
- name: quay-pull-secret
  files:
  - .dockerconfigjson=files/quay-pull-secret.json
  type: kubernetes.io/dockerconfigjson

# This expects to find an AAP license manifest
# in files/license.zip.
- name: config-as-code-manifest-ig
  options:
    labels:
      cloudkit.openshift.io/project: cloudkit-aap
  files:
  - license.zip=files/license.zip
