#
# Copyright (c) 2025 Red Hat Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: fulfillment-service-development

# Resources for fulfillment service (uses shared namespace)
resources:
  - ../../../base/fulfillment-service 
  - route.yaml

# Patches to fix namePrefix issues with cert-manager
patches:
- target:
    kind: Certificate
    name: ca-certificate
  patch: |-
    - op: replace
      path: /spec/secretName
      value: dev-ca-key
    - op: replace
      path: /spec/issuerRef/name
      value: dev-ca-issuer
- target:
    kind: Certificate
    name: fulfillment-api
  patch: |-
    - op: replace
      path: /spec/secretName
      value: dev-fulfillment-service-tls
    - op: replace
      path: /spec/issuerRef/name
      value: dev-issuer
    - op: replace
      path: /spec/dnsNames
      value: 
        - localhost
        - fulfillment-api
        - dev-fulfillment-api-foobar.apps.hcp.local.lab
- target:
    kind: Certificate
    name: fulfillment-database-client
  patch: |-
    - op: replace
      path: /spec/secretName
      value: dev-fulfillment-database-client-cert
    - op: replace
      path: /spec/issuerRef/name
      value: dev-issuer
- target:
    kind: Certificate
    name: fulfillment-database-server
  patch: |-
    - op: replace
      path: /spec/secretName
      value: dev-fulfillment-database-server-cert
    - op: replace
      path: /spec/issuerRef/name
      value: dev-issuer
    - op: replace
      path: /spec/dnsNames
      value: 
        - fulfillment-database
        - dev-fulfillment-database
# - target:
#     kind: Issuer
#     name: ca-issuer
#   patch: |-
#     - op: replace
#       path: /metadata/name
#       value: dev-ca-issuer
- target:
    kind: Issuer
    name: issuer
  patch: |-
    - op: replace
      path: /spec/ca/secretName
      value: dev-ca-key
# Fix deployment volume secret names
- target:
    kind: Deployment
    name: fulfillment-service
  patch: |-
    - op: replace
      path: /spec/template/spec/volumes/2/secret/secretName
      value: dev-fulfillment-database-client-cert
    - op: replace
      path: /spec/template/spec/volumes/4/secret/secretName
      value: dev-fulfillment-service-tls
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Always
    - op: replace
      path: /spec/template/spec/containers/1/imagePullPolicy
      value: Always
- target:
    kind: Deployment
    name: fulfillment-controller
  patch: |-
    - op: replace
      path: /spec/template/spec/volumes/0/secret/secretName
      value: dev-fulfillment-service-tls
    - op: replace
      path: /spec/template/spec/containers/0/command/7
      value: --grpc-server-address=dev-fulfillment-api:8000
    - op: add
      path: /spec/template/spec/containers/0/command/-
      value: --grpc-server-insecure
- target:
    kind: StatefulSet
    name: fulfillment-database
  patch: |-
    - op: replace
      path: /spec/template/spec/volumes/0/secret/secretName
      value: dev-fulfillment-database-server-cert
# Fix database hostname via environment variable
- target:
    kind: Deployment
    name: fulfillment-service
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: dev-fulfillment-database
# Add imagePullSecrets for private registry access
- target:
    kind: Deployment
    name: fulfillment-service
  patch: |-
    - op: add
      path: /spec/template/spec/imagePullSecrets
      value:
      - name: dev-quay-pull-secret
- target:
    kind: Deployment
    name: fulfillment-controller
  patch: |-
    - op: add
      path: /spec/template/spec/imagePullSecrets
      value:
      - name: dev-quay-pull-secret
# Fix authorization rules to use prefixed service account names
- target:
    kind: ConfigMap
    name: fulfillment-service-config
  patch: |-
    - op: replace
      path: /data/rules.yaml
      value: |
        #
        # Copyright (c) 2025 Red Hat Inc.
        #
        # Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
        # the License. You may obtain a copy of the License at
        #
        #   http://www.apache.org/licenses/LICENSE-2.0
        #
        # Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an
        # "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
        # specific language governing permissions and limitations under the License.
        #

        - name: Allow reflection and health to everyone
          action: allow
          condition: method.startsWith('/grpc.reflection.') || method.startsWith('/grpc.health.')

        - name: Allow specific methods to client
          action: allow
          condition: |
            subject.name == 'system:serviceaccount:${NAMESPACE}:dev-client' &&
            method in [
              '/events.v1/Watch',
              '/fulfillment.v1.ClusterTemplates/Get',
              '/fulfillment.v1.ClusterTemplates/List',
              '/fulfillment.v1.Clusters/Delete',
              '/fulfillment.v1.Clusters/Get',
              '/fulfillment.v1.Clusters/GetKubeconfig',
              '/fulfillment.v1.Clusters/GetKubeconfigViaHttp',
              '/fulfillment.v1.Clusters/List',
              '/fulfillment.v1.Clusters/Update',
              '/fulfillment.v1.HostClasses/Get',
              '/fulfillment.v1.HostClasses/List',
            ]

        - name: Allow everything to admin and controller
          action: allow
          condition: |
            subject.name in [
              'system:serviceaccount:${NAMESPACE}:dev-admin',
              'system:serviceaccount:${NAMESPACE}:dev-controller',
              'system:serviceaccount:${NAMESPACE}:dev-controller-manager',
            ]


commonAnnotations:
  cloudkit.io/organization: cloudkit
  cloudkit.io/project: fulfillment-service


generatorOptions:
  disableNameSuffixHash: true

# Override authorization rules for development environment with dev- prefix
configMapGenerator:
- name: fulfillment-service-config
  files:
  - rules.yaml
  behavior: merge

# images:
# - name: ghcr.io/innabox/fulfillment-service
#   newName: quay.io/rh-ee-jkary/fulfillment-service
#   newTag: latest
