apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: innabox-aap
spec:
  controller:
    disabled: false
  eda:
    disabled: false
  hub:
    disabled: true
  image_pull_policy: IfNotPresent
  lightspeed:
    disabled: true
  no_log: true
  redis_mode: standalone
  route_tls_termination_mechanism: Edge
