apiVersion: v1
kind: Secret
metadata:
  name: cluster-fulfillment-ig
type: Opaque
stringData:
  credentials: |
    # Setup here the credentials required for cluster fulfillment playbooks (AWS, OpenStack, ...)
