---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: template-publisher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-controller-token
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    resourceNames: ["template-publisher"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aap-fulfillment-template-publisher-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: create-controller-token
subjects:
  - kind: ServiceAccount
    name: template-publisher
