apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    component: database

resources:
- sa.yaml
- rbac.yaml
- pvc.yaml
- service.yaml
- statefulset.yaml
- server-cert.yaml
- client-cert.yaml

configMapGenerator:
- name: fulfillment-database-server
  files:
  - files/server.conf
- name: fulfillment-database-access
  files:
  - files/access.conf
